version: '3.1'

services:

  db:
    image: 'postgres:13.7-alpine'
    container_name: capstone-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"